const translations = {
  id: {
    "hero-text": "Jelajahi pesona Pulau Bintan dengan pengalaman wisata terbaik yang telah kami pilih untuk Anda! Destinasi pantai berpasir putih yang memukau setiap wisata menawarkan keindahan yang tak terlupakan.",
    "hero-text2": "Jelajahi destinasi alam pulau bintan, nikmati pemandangan yang memukau, dan rasakan keramahan masyarakat lokal dalam petualangan seru Anda di tanah penuh pesona ini.",
    "teks1": "Pantai",
    "hero-text3": "Temukan keindahan sejati di Kepulauan Riau, surga tropis yang menyajikan panorama alam menakjubkan, pantai berpasir putih, dari pulau bintan",
    "hero-text4": "Setiap perjalanan dimulai dari langkah pertama. Biarkan Keep Travel yang menemanimu menjelajahi keindahan Tanjung Pinang dan Bintan!. Mau healing di pantai cantik atau eksplorasi sudut-sudut seru pulau? Dengan Keep Travel, semua jadi lebih mudah. Booking tempat wisata favorit, sewa motor untuk jalan-jalan tanpa batas, dan nikmati liburan yang benar-benar bebas — semua dalam genggamanmu. Mulai sekarang, tak perlu ribet lagi cari transportasi atau tiket masuk. Keep Travel hadir buat kamu yang mau liburan simpel, santai, dan penuh kenangan seru. Karena momen indah itu layak didapat dengan cara yang gampang.",
    "hero-text5": "Terletak di pesisir timur Pulau Bintan, Pantai Trikora adalah surga tropis dengan pasir putih yang lembut dan air laut yang jernih kebiruan. Pantai ini menjadi destinasi favorit para wisatawan karena keindahan alamnya yang masih alami serta suasananya yang tenang. Cocok untuk bersantai, berenang, atau sekadar menikmati pemandangan laut yang memukau.",
    "hero-text6": "Autentik dan menenangkan, Pantai Trikora menawarkan pengalaman wisata yang jauh dari hiruk pikuk kota. Jangan lupa mencoba kuliner laut segar dari warung-warung sekitar pantai.",
    "hero-text7": "Pantai Trikora bukan sekadar destinasi wisata biasa. Keindahan pasir putih yang membentang luas, ombak yang tenang, serta hamparan pohon kelapa menciptakan suasana tropis yang sempurna untuk melepas penat. Suasana yang damai menjadikannya tempat ideal untuk liburan bersama keluarga, pasangan, atau bahkan solo traveler.",
    "hero-text8": "Dibandingkan pantai lain, Trikora menawarkan pengalaman yang lebih otentik dan alami, jauh dari keramaian wisata komersial. Di sini, Anda bisa menikmati keindahan alam yang sesungguhnya tanpa gangguan.",
    "hero-text9": "Pantai Trikora memiliki keindahan yang tiada tara, dengan sunset dan sunrise yang menyejukkan mata. Sangat cocok bagi pelancong yang mencari kedamaian dan ingin merasakan suasana pantai yang masih alami.",
    "teks-why1":"Pantai Trikora merupakan salah satu destinasi wisata unggulan yang terletak di Pulau Bintan, Kepulauan Riau. Dengan garis pantai yang membentang panjang, pasir putih yang lembut, dan air laut yang jernih kebiruan, Trikora menghadirkan pesona alam yang masih asri dan alami. Pantai ini sangat direkomendasikan bagi wisatawan yang mencari ketenangan dan keindahan tropis jauh dari keramaian kota. Selain keindahan panoramanya, Pantai Trikora juga memiliki nilai budaya dan sejarah yang melekat, menjadikannya tempat yang ideal untuk wisata edukatif sekaligus rekreasi.",
    "teks-why2":"Akses menuju pantai ini relatif mudah, dengan infrastruktur yang terus berkembang serta tersedia berbagai penginapan dan fasilitas wisata yang memadai. Aktivitas seperti snorkeling, berenang, memancing, hingga menikmati kuliner laut lokal menjadi daya tarik tambahan yang tidak boleh dilewatkan. Dengan kombinasi keindahan alam, kenyamanan, dan nilai sejarahnya, Pantai Trikora adalah pilihan tepat untuk perancangan destinasi wisata yang berkesan dan berkelanjutan.",
    "teks-why3":"Pantai Trikora, yang terletak di sisi timur Pulau Bintan, merupakan permata tersembunyi di Kepulauan Riau yang menawarkan pengalaman wisata pantai yang autentik dan memikat. Keindahan alamnya yang alami, dengan hamparan pasir putih bersih, batu-batu granit eksotis, serta air laut yang tenang dan jernih, menjadikan Pantai Trikora sebagai destinasi yang ideal untuk relaksasi maupun eksplorasi alam. Dibandingkan dengan destinasi pantai lainnya, Trikora memiliki keunggulan dalam suasana yang lebih tenang dan belum terlalu ramai oleh wisatawan, sehingga cocok bagi pelancong yang mencari kedamaian dan ingin merasakan suasana pantai yang masih alami. Pantai ini juga sangat cocok dijadikan lokasi untuk desain wisata yang mengedepankan konsep eco-tourism, karena lingkungannya yang masih sangat terjaga dan bersih.",
    "teks-why4":"Selain keindahan alam, Pantai Trikora juga memiliki nilai sejarah dan budaya yang menarik untuk diangkat dalam desain wisata. Wilayah ini pernah menjadi bagian dari sejarah perjuangan nasional, yang dapat dikaitkan dengan edukasi wisata sejarah lokal. Fasilitas di sekitar pantai pun mulai berkembang—mulai dari resort, penginapan lokal (homestay), tempat makan khas laut, hingga penyedia jasa aktivitas wisata seperti snorkeling, kano, dan tur laut. Potensi pemberdayaan masyarakat lokal juga besar, sehingga sangat memungkinkan untuk menciptakan konsep wisata berbasis komunitas yang inklusif dan berkelanjutan.",
    "hs1": "Pantai Trikora adalah salah satu pantai yang ada di Pulau Bintan, Kepulauan Riau, Indonesia. Pantai ini memiliki hamparan pasir putih sepanjang kurang lebih 25 kilometer. Dengan keindahan eksotis dan cerita sejarah yang melekat, Pantai Trikora memiliki daya tarik tersendiri bagi wisatawan dari berbagai negara, sehingga menjadi salah satu destinasi bahari unggulan di Bintan, Kepulauan Riau. Namun, tahukah Anda bahwa di balik keindahan Pantai Trikora terdapat latar belakang cerita dan asal usul nama pantai ini? Tentu saja, tidak semua kalangan masyarakat mengetahui alasan mengapa pantai ini dinamakan Pantai Trikora.",
    "hs2": "Pantai Trikora adalah nama sebuah pantai yang terletak tepatnya di Desa Malang Rapat, Kabupaten Bintan, yang berjarak lebih kurang 46 kilometer dari pusat kota Tanjung Pinang. Cerita singkat asal usul nama Trikora berasal dari petikan kata Tri Komando Rakyat, yang terkait dengan tragedi konflik selama kurang lebih dua tahun antara Indonesia dan Malaysia, dari tanggal 19 Desember 1961 hingga 15 Agustus 1962.",
    "hs3": "Pembentukan Trikora dilakukan di bawah kepemimpinan Presiden Soekarno pada masa tersebut sebagai upaya menentukan masa depan penguasaan wilayah, termasuk Sabah, Sarawak, dan Brunei Darussalam. Pembentukan Trikora, atau Tri Komando Rakyat, diumumkan oleh Presiden Soekarno di Alun-Alun Yogyakarta, dan pergerakan pun dilakukan di Pulau Bintan. Pulau ini dipilih karena merupakan tempat yang strategis dalam menjaga pertahanan, sekaligus menjadi garis pantai terdekat dengan perbatasan Indonesia-Malaysia. Konflik yang pernah terjadi antara Indonesia dan Malaysia berawal dari keinginan Federasi Malaya, yang lebih dikenal sebagai Persekutuan Tanah Melayu (Malaysia), pada tahun 1961 untuk menggabungkan Brunei Darussalam, Sabah, dan Sarawak ke dalam kekuasaan Malaysia. Namun, hal ini tidak disetujui oleh Manila.",
    "hs4": "Keinginan pembentukan Federasi Malaya juga ditentang langsung oleh Presiden Soekarno, yang menganggap bahwa pembentukan tersebut merupakan bentuk kolonialisme dan imperialisme dalam wujud baru. Selain itu, Soekarno menilai hal itu sebagai bentuk dukungan terhadap berbagai gangguan keamanan, kemerdekaan, dan pemberontakan di Indonesia setelah Proklamasi Kemerdekaan dideklarasikan pada 17 Agustus 1945"
  },
  en: {
    "hero-text": "Explore the charm of Bintan Island with the best travel experiences we've selected for you! White sandy beach destinations enchant every traveler with unforgettable beauty.",
    "hero-text2": "Explore the natural destinations of bintan island, enjoy the breathtaking scenery, and experience the hospitality of the local people on your exciting adventure in the this land of enchantment.",
    "teks1": "Beach",
    "hero-text3": "Discover the true beauty of the Riau Islands, a tropical paradise featuring stunning natural panoramas, white sandy beaches, from the island of Bintan.",
    "hero-text4": "Every journey begins with the first step. Let Keep Travel accompany you to explore the beauty of Tanjung Pinang and Bintan!.Want to heal on a beautiful beach or explore the island's most exciting corners? With Keep Travel, everything is easier. Book your favorite attractions, rent a motorbike for unlimited sightseeing, and enjoy a truly carefree vacation - all at your fingertips. From now on, look no further for transportation or entrance tickets. Keep Travel is here for those of you who want a simple, relaxing, and memorable vacation. Because beautiful moments deserve to be had the easy way.",
    "hero-text5": "Located on the east coast of Bintan Island, Trikora Beach is a tropical paradise with soft white sand and clear bluish sea water. This beach is a favorite destination for tourists because of its unspoiled natural beauty and calm atmosphere. It's a great place to relax, swim, or simply enjoy the stunning ocean views.",
    "hero-text6": "Authentic and relaxing, Trikora Beach offers a travel experience away from the hustle and bustle of the city. Don't forget to try the fresh seafood from the stalls around the beach.",
    "hero-text7": "Trikora Beach is not just another tourist destination. The beauty of the wide stretches of white sand, calm waves, and coconut trees create a tropical atmosphere that is perfect for unwinding. The peaceful atmosphere makes it an ideal place for a vacation with family, couples, or even solo travelers.",
    "hero-text8": "Compared to other beaches, Trikora offers a more authentic and natural experience, away from the crowds of commercial tourism. Here, you can enjoy the true beauty of nature without distractions.",
    "hero-text9": "Trikora Beach has an incomparable beauty, with sunset and sunrise that soothes the eyes. It is suitable for travelers who seek peace and want to feel the atmosphere of an unspoiled beach.",
    "teks-why1": "Trikora Beach is one of the leading tourist destinations located on Bintan Island, Riau Islands. With a long stretch of coastline, soft white sand, and clear bluish sea water, Trikora presents a natural charm that is still beautiful and natural. This beach is highly recommended for travelers looking for tranquility and tropical beauty away from the hustle and bustle of the city. In addition to its panoramic beauty, Trikora Beach also has an inherent cultural and historical value, making it an ideal place for both educational and recreational tourism.",
    "teks-why2": "Access to this beach is relatively easy, with infrastructure that continues to develop and adequate lodging and tourist facilities available. Activities such as snorkeling, swimming, fishing, and enjoying local seafood are additional attractions that should not be missed. With its combination of natural beauty, comfort and historical value, Trikora Beach is the right choice for designing a memorable and sustainable tourist destination.",
    "teks-why3": "Trikora Beach, located on the eastern side of Bintan Island, is a hidden gem in the Riau Islands that offers an authentic and enchanting beach tourism experience. Its natural beauty, with pristine white sand, exotic granite boulders, and calm, clear waters, makes Trikora Beach an ideal destination for relaxation and nature exploration. Compared to other beach destinations, Trikora has the advantage of a quieter atmosphere and is not too crowded with tourists, making it suitable for travelers who are looking for peace and want to feel the atmosphere of an unspoiled beach. This beach is also very suitable as a location for tourism design that emphasizes the concept of eco-tourism, because the environment is still very well preserved and clean.",
    "teks-why4": "In addition to its natural beauty, Trikora Beach also has historical and cultural values that are interesting to raise in tourism design. The area was once part of the history of the national struggle, which can be linked to local history tourism education. Facilities around the beach have also begun to develop-from resorts, local inns (homestays), seafood eateries, to tourist activity service providers such as snorkeling, canoeing, and sea tours. The potential for empowering local communities is also great, making it possible to create an inclusive and sustainable community-based tourism concept.",
    "hs1": "Trikora Beach is one of the beaches on Bintan Island, Riau Islands, Indonesia. This beach has a stretch of white sand along approximately 25 kilometers. With its exotic beauty and historical story, Trikora Beach has its own charm for tourists from various countries, making it one of the leading marine destinations in Bintan, Riau Islands. However, did you know that behind the beauty of Trikora Beach there is a background story and the origin of the name of this beach? Of course, not all people know the reason why this beach is called Trikora Beach.",
    "hs2": "Trikora Beach is the name of a beach located precisely in Malang Rapat Village, Bintan Regency, which is approximately 46 kilometers from Tanjung Pinang city center. The short story of the origin of the name Trikora comes from the word Tri Komando Rakyat, which is related to the tragedy of the conflict for approximately two years between Indonesia and Malaysia, from December 19, 1961 to August 15, 1962.",
    "hs3": "The formation of Trikora was carried out under the leadership of President Soekarno during this time as an effort to determine the future of territorial control, including Sabah, Sarawak, and Brunei Darussalam. The formation of Trikora, or Tri Komando Rakyat, was announced by President Soekarno in Yogyakarta Square, and the movement was carried out on Bintan Island. This island was chosen because it was a strategic place to maintain defense, as well as being the closest coastline to the Indonesia-Malaysia border. The conflict between Indonesia and Malaysia began with the desire of the Federation of Malaya, better known as Persekutuan Tanah Melayu (Malaysia), in 1961 to incorporate Brunei Darussalam, Sabah and Sarawak into Malaysia. However, this was not approved by Manila.",
    "hs4": "The desire to form a Federation of Malaya was also directly opposed by President Soekarno, who considered it a new form of colonialism and imperialism. In addition, Soekarno considered it as a form of support for various security disturbances, independence, and rebellions in Indonesia after the Proclamation of Independence was declared on August 17, 1945."
},
};

function applyLanguage(lang) {
  for (const id in translations[lang]) {
    const el = document.getElementById(id);
    if (el) {
      el.innerText = translations[lang][id];
    }
  }
}
